name: built_to_cache_test
version: 2.5.0

environment:
  sdk: '>=1.24.3 <3.0.0'

dependencies:
  sass_builder: ">= 1.2.0 <3.0.0"

dev_dependencies:
  # public dependencies
  build_runner: ">=0.6.0 <2.0.0"
  build_test: ">=0.9.0 <2.0.0"
  build_web_compilers: ">=0.2.0 <2.0.0"
  test: any

